---
/etc/query_service/ldf-config.json:
  template: ldf-config.json.j2
  remote_vars: /etc/query_service/vars.yaml

/etc/query_service/vars.sh:
  template: vars.sh.j2
  remote_vars: /etc/query_service/vars.yaml

