---
/etc/wdqs/RWStore.properties:
  template: RWStore.properties.j2
  remote_vars: /etc/wdqs/vars.yaml

/etc/wdqs/ldf-config.json:
  template: ldf-config.json.j2
  remote_vars: /etc/wdqs/vars.yaml

/etc/wdqs/vars.sh:
  template: vars.sh.j2
  remote_vars: /etc/wdqs/vars.yaml

